source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'sinatra-formhelpers-ng'
gem 'sinatra-contrib'
gem 'sinatra-assetpack'
gem 'yui-compressor'
gem 'sass'
gem 'json'
gem 'thin'

gem 'rack-test'
gem 'rspec'
gem 'fuubar'
